lint:
 stage: test
 script:
 - pip install yapf
 - yapf --recursive . --diff --style google
 only:
 - pushes


unittest:
 stage: test
 script:
 - pip install -r requirements.txt
 - pytest -v
 only:
 - pushes



prod:
 image: google/cloud-sdk:alpine
 stage: deploy
 environment: Production
 only:
 - main
 script:
 - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
 - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
 - gcloud --quiet --project $brainiacs1 app deploy 