<lint>:
 stage: test
 script:
 - pip install yapf
 - yapf --recursive . --diff --style google
 only:
 - pushes


<unittest>:
 stage: test
 needs: 
 - pipeline: test
   job: lint
 script:
 - pip install -r requirements.txt
 - pytest -v
 only:
 - pushes